services:
  - type: web
    name: traval-backend
    env: java
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: traval-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: traval-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: traval-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: traval-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: traval-db
          property: password

databases:
  - name: traval-db
    databaseName: traval
    user: traval_user